ares.components += z80

ares.objects += ares-pv1000-cpu
ares.objects += ares-pv1000-vdp
ares.objects += ares-pv1000-system
ares.objects += ares-pv1000-cartridge
ares.objects += ares-pv1000-controller

$(object.path)/ares-pv1000-cpu.o:        $(ares.path)/pv1000/cpu/cpu.cpp
$(object.path)/ares-pv1000-vdp.o:        $(ares.path)/pv1000/vdp/vdp.cpp
$(object.path)/ares-pv1000-system.o:     $(ares.path)/pv1000/system/system.cpp
$(object.path)/ares-pv1000-cartridge.o:  $(ares.path)/pv1000/cartridge/cartridge.cpp
$(object.path)/ares-pv1000-controller.o: $(ares.path)/pv1000/controller/controller.cpp
